# Generated by Django 5.0.6 on 2024-06-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='is_read_by_admin',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_read_by_handling_officer',
            field=models.BooleanField(default=False),
        ),
    ]
