# Generated by Django 5.0.6 on 2024-06-15 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='project',
            name='files',
        ),
    ]
