# Generated by Django 5.0.6 on 2024-06-12 12:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
